"""Bounded handling of images generated by Mistral."""

from __future__ import annotations

import asyncio
import warnings
from contextlib import suppress
from dataclasses import dataclass
from io import BytesIO
from typing import TYPE_CHECKING, cast

import httpx
from homeassistant.core import HomeAssistant
from PIL import Image, UnidentifiedImageError

from .api import (
    async_delete_generated_file,
    async_download_image_file,
    async_start_image_generation,
)
from .const import (
    IMAGE_CLEANUP_TIMEOUT,
    LOGGER,
    MAX_GENERATED_IMAGE_BYTES,
    REQUEST_TIMEOUT_MS,
)

if TYPE_CHECKING:
    from mistralai.client import Mistral

_IMAGE_MIME_TYPES = {
    "GIF": "image/gif",
    "JPEG": "image/jpeg",
    "PNG": "image/png",
    "WEBP": "image/webp",
}


class ImageGenerationError(Exception):
    """A local generated-image failure with a translated Home Assistant key."""

    def __init__(self, translation_key: str) -> None:
        """Keep file content and provider identifiers out of error text."""
        super().__init__(translation_key)
        self.translation_key = translation_key


@dataclass(frozen=True, slots=True)
class GeneratedImage:
    """One locally validated generated image."""

    data: bytes
    mime_type: str


async def _await_shielded(task: asyncio.Task[None]) -> None:
    """Let a bounded resource task finish despite repeated caller cancellation."""
    cancelled = False
    while not task.done():
        try:
            await asyncio.shield(task)
        except asyncio.CancelledError:
            cancelled = True
    await task
    if cancelled:
        raise asyncio.CancelledError


async def _read_bounded_image(response: httpx.Response) -> bytes:
    """Read raw identity-encoded bytes; cleanup owns response closure."""
    if response.headers.get("content-encoding", "identity").casefold() != "identity":
        raise ImageGenerationError("image_response_invalid")
    content_length = response.headers.get("content-length")
    if content_length is not None:
        try:
            if int(content_length) > MAX_GENERATED_IMAGE_BYTES:
                raise ImageGenerationError("image_response_too_large")
        except ValueError:
            # A bad header does not bypass the bound enforced per chunk.
            pass

    output = bytearray()
    # Response.aiter_bytes() implicitly closes at EOF. A cancellation during
    # that closure marks the response closed before its stream has closed, so
    # use the public stream interface and close it in our bounded finalizer.
    stream = cast(httpx.AsyncByteStream, response.stream)
    async for chunk in stream:
        if len(output) + len(chunk) > MAX_GENERATED_IMAGE_BYTES:
            raise ImageGenerationError("image_response_too_large")
        output.extend(chunk)
    if not output:
        raise ImageGenerationError("image_response_invalid")
    return bytes(output)


def _verified_mime_type(data: bytes) -> str:
    """Identify and fully decode an allowed image away from HA's event loop."""
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            with Image.open(BytesIO(data)) as image:
                mime_type = _IMAGE_MIME_TYPES.get(image.format or "")
                if mime_type is None:
                    raise ImageGenerationError("image_response_invalid")
                image.verify()
            with Image.open(BytesIO(data)) as image:
                image.load()
    except (
        UnidentifiedImageError,
        OSError,
        ValueError,
        Image.DecompressionBombWarning,
        Image.DecompressionBombError,
    ):
        raise ImageGenerationError("image_response_invalid") from None
    return mime_type


async def _cleanup_resources(
    client: Mistral, file_ids: tuple[str, ...], response: httpx.Response | None
) -> None:
    """Close the response and delete all known files within ten seconds total."""
    closed = response is None
    deleted = [False] * len(file_ids)

    async def close_response() -> None:
        nonlocal closed
        if response is None:
            return
        try:
            await response.aclose()
            closed = True
        except Exception:
            pass

    async def delete_one(index: int, file_id: str) -> None:
        with suppress(Exception):
            deleted[index] = await async_delete_generated_file(client, file_id)

    try:
        async with asyncio.timeout(IMAGE_CLEANUP_TIMEOUT):
            await asyncio.gather(
                close_response(),
                *(delete_one(index, file_id) for index, file_id in enumerate(file_ids)),
            )
    except TimeoutError:
        pass
    if not closed:
        LOGGER.warning("Mistral generated-image download response did not close")
    if not all(deleted):
        LOGGER.warning("Mistral generated-file deletion was not confirmed")


async def async_generate_image(
    hass: HomeAssistant,
    client: Mistral,
    model: str,
    prompt: str,
    attachments: list[str],
) -> GeneratedImage:
    """Generate, download, validate, and best-effort delete one image."""
    file_ids: tuple[str, ...] = ()
    response: httpx.Response | None = None
    try:
        async with asyncio.timeout(REQUEST_TIMEOUT_MS / 1000):
            file_ids = await async_start_image_generation(
                client, model, prompt, attachments
            )
            if not file_ids:
                raise ImageGenerationError("image_response_not_found")
            response = await async_download_image_file(client, file_ids[0])
            data = await _read_bounded_image(response)
            mime_type = await hass.async_add_executor_job(_verified_mime_type, data)
            return GeneratedImage(data=data, mime_type=mime_type)
    finally:
        if response is not None or file_ids:
            await _await_shielded(
                asyncio.create_task(_cleanup_resources(client, file_ids, response))
            )
